server:
  port: 8204 # 服务端口
spring:
  application:
    name: service-order # 服务名
  profiles:
    active: dev #运行级别
  # mysql配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jsyy_order?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lzq2686105
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis配置
  redis:
    database: 0
    host: 101.35.181.165
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 101.35.181.165:8848

  # rabbitmq配置
  rabbitmq:
    host: 101.35.181.165
    port: 5672
    username: root
    password: root

  # 允许存在多个Feign调用相同Service的接口
  main:
    allow-bean-definition-overriding: true

# 微信配置
weixin:
  appid: wx74862e0dfcf69954
  partner: 1558950191
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  # 退款证书
  cert: E:\\javaStudy\\yygh_parent\\service\\service_order\\src\\main\\resources\\cert\\apiclient_cert.p12